language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=sklearn_xarray
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7"
    - DISTRIB="conda" PYTHON_VERSION="3.5"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"
      #NUMPY_VERSION="1.13.1" SCIPY_VERSION="1.0.0" CYTHON_VERSION="0.25.2"

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test.sh
after_success: source build_tools/travis/success.sh
