name: sklearn-xarray
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - xarray
  - six
  - pytest
  - matplotlib
  - sphinx
  - pillow
  - sphinx-gallery
  - sphinx_rtd_theme
  - numpydoc
