package:
  name: sklearn-xarray
  version: 0.3.0

source:
  git_rev: "0.3.0"
  git_url: https://github.com/phausamann/sklearn-xarray.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - python
    - scikit-learn
    - xarray
    - pandas
    - six

about:
  home: https://github.com/phausamann/sklearn-xarray
  license: BSD-3
  license_file: LICENSE
