{% set data = load_setup_py_data() %}

package:
  name: sklearn-xarray
  version: {{ data['version'] }}

source:
  path: ../..

build:
  noarch: python
  number: 1
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - xarray
    - pandas
    - six

test:
  source_files:
    - sklearn_xarray/tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest --cov=sklearn_xarray

about:
  home: https://github.com/phausamann/sklearn-xarray
  license: BSD-3
  license_file: LICENSE
